[project]
name = "video-overlay-application"
version = "0.1.0"
description = ""

dependencies = [
    "flask>=3.0.0",
    "opencv-python>=4.8.1.78",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
